In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    755     68   John  January      Q1
1  2023-01-02       B   West    956     72   Mary  January      Q1
2  2023-01-03       C  North    821     99    Bob  January      Q1
3  2023-01-04       D  South    865     57  Alice  January      Q1
4  2023-01-05       A   East    625     84   John  January      Q1
5  2023-01-06       B   West    668     52   Mary  January      Q1
6  2023-01-07       C  North    700     56    Bob  January      Q1
7  2023-01-08       D  South    254     99  Alice  January      Q1
8  2023-01-09       A   East    800     53   John  January      Q1
9  2023-01-10       B   West    234     93   Mary  January      Q1
10 2023-01-11       C  North    712     75    Bob  January      Q1
11 2023-01-12       D  South    249     19  Alice  January      Q1
12 2023-01-13       A   East    801     69   John  January      Q1
13 2023-01-14       B   West    681     96   Mary  January      Q1
14 2023-01-15       C  North    796     32    Bob  January      Q1
15 2023-01-16       D  South    323     84  Alice  January      Q1
16 2023-01-17       A   East    654     76   John  January      Q1
17 2023-01-18       B   West    484     79   Mary  January      Q1
18 2023-01-19       C  North    610     95    Bob  January      Q1
19 2023-01-20       D  South    933     25  Alice  January      Q1

In [4]:
pd.pivot_table(df, values = 'Sales', index = 'Region', columns='Product', aggfunc = 'median')

Product      A      B      C      D
Region
East     755.0    NaN    NaN    NaN
North      NaN    NaN  712.0    NaN
South      NaN    NaN    NaN  323.0
West       NaN  668.0    NaN    NaN

In [ ]:
pivot2 = pd.pivot_table(df, values = ['Sales', 'Units'], index = 'Region', columns = 'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     622.6    NaN    NaN    NaN  59.0   NaN   NaN   NaN
North      NaN    NaN  737.4    NaN   NaN   NaN  69.2   NaN
South      NaN    NaN    NaN  445.8   NaN   NaN   NaN  46.0
West       NaN  490.6    NaN    NaN   NaN  84.0   NaN   NaN

Cross tabs

In [ ]:
pd.crosstab(df['Region'])